[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = [
  "tests",
  "notifications/crates/*",
  "notifications/zomes/coordinator/*",
  "notifications/zomes/integrity/*",
  "providers/*/crates/*",
  "providers/*/zomes/coordinator/*",
  "providers/*/zomes/integrity/*",
]
resolver = "2"

[workspace.dependencies]
hdi = "=0.3.4"
hdk = "=0.2.4"
serde = "=1.0.166"

[workspace.dependencies.hc_zome_notifications_coordinator]
path = "notifications/zomes/coordinator/notifications"

[workspace.dependencies.hc_zome_notifications_integrity]
path = "notifications/zomes/integrity/notifications"

[workspace.dependencies.hc_zome_notifications_types]
path = "notifications/crates/hc_zome_notifications_types"

[workspace.dependencies.holochain]
default-features = false
features = ["test_utils"]
version = "0.2.2"
