[package]
name = "profiles_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles_integrity"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

hc_zome_profiles_integrity = "0.2"
